spring:
  config:
    activate:
      on-profile: local
  application:
    name: repkit
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true

repkit:
  logout-success-url: http://localhost:5173/login

---

spring:
  config:
    activate:
      on-profile: prod
  application:
    name: repkit
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: ${PORT:8080}
  address: 0.0.0.0

repkit:
  logout-success-url: https://repkit.vercel.app